name: 'mongo'
services:
    mongo:
        image: mongo:latest
        hostname: mongo
        container_name: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
            MONGO_INITDB_DATABASE: mydb
        networks:
            - mongo

    mongo-express:
        image: mongo-express:latest
        hostname: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: admin
            ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
            ME_CONFIG_BASICAUTH: false
        networks:
            - mongo

networks:
    mongo:
        driver: bridge
